// Project data for the machine, from Nikhil's resume. `name` prints on the can (keep it short),
// `short` on the price tag, `title`/`summary`/facts in the project view.
const cols = ['yellow', 'teal', 'pink', 'blue', 'orange', 'lime', 'pink', 'violet', 'teal', 'orange', 'blue', 'yellow'];
const glyphs = ['circle', 'bars', 'diamond', 'ring', 'tri', 'plus', 'plus', 'circle', 'bars', 'tri', 'ring', 'diamond'];
const ITEMS = [
  { name: 'MEMORY LAYER', short: 'MEMORY', cat: 'WORK', title: 'Agentic Omnichannel Memory', summary: 'A cross-channel identity-resolution and unified memory layer for WhatsApp, website, Instagram, Messenger and voice, so agentic bots keep short- and long-term memory across sessions.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'Python · LLMs · Customer Data Platform', status: 'In production', result: '98% cross-channel match accuracy, zero orphaned sessions.' },
  { name: 'AGENT ORCH.', short: 'AGENTS', cat: 'WORK', title: 'Multi-Agent Orchestration', summary: 'A low-latency multi-agent system on LangGraph with async execution, smart caching and optimized message passing, using MCP to pass context and call in-house and external tools.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'LangGraph · MCP · Python async', status: 'In production', result: 'Round trips under 5 seconds.' },
  { name: 'PDF VISION', short: 'PDF IMAGES', cat: 'WORK', title: 'Multi-Modal PDF Image Retrieval', summary: 'Extracts images from PDFs, reads the surrounding headings and text, writes LLM captions and indexes them in Pinecone with image URLs as metadata.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'Pinecone · LLM captioning · RAG', status: 'In production', result: 'Agents answer with the right text and image in one reply.' },
  { name: 'AUTO BOT', short: 'AUTO POC', cat: 'WORK', title: 'Automotive Conversational AI', summary: 'A multimodal bot that identifies users by phone number, pulls their vehicle data, and diagnoses engine faults from uploaded audio.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'Audio classification · Multimodal LLM', status: 'Proof of concept', result: 'Unresolved cases route straight to service-centre booking.' },
  { name: 'API LOGS', short: 'API LOGS', cat: 'WORK', title: 'Unified API Logging & Observability', summary: 'Captures every inbound API request across client campaigns: Django middleware intercepts without blocking, Celery drains a RabbitMQ broker into ClickHouse.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'Django · Celery · RabbitMQ · ClickHouse', status: 'In production', result: 'Client dashboard for live auditing, latency tracing and failures.' },
  { name: 'ASK-AI', short: 'ASK-AI', cat: 'WORK', title: 'Cross-Channel “Ask-AI” Analytics Agent', summary: 'Ask how a campaign performed across every channel in one sentence. A deterministic multi-agent pipeline splits intent and routes to channel-specific fetchers.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'Multi-agent · NL analytics · Charts', status: 'In production', result: 'Answers render with charts generated inline.' },
  { name: 'RAG TUNING', short: 'RAG TUNING', cat: 'WORK', title: 'RAG Pipeline Optimization', summary: 'Diagnosed ingestion gaps, refined chunking and re-ranking, and deployed cheaper embedding models with better cleaning for scraped web content.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'RAG · Embeddings · Re-ranking', status: 'In production', result: 'Better retrieval at lower embedding cost.' },
  { name: 'REDIS CACHE', short: 'REDIS CACHE', cat: 'WORK', title: 'Redis Semantic Query Cache', summary: 'A Redis-backed semantic cache for repeated user queries, answering high-frequency intents without calling the model.', role: 'Backend AI Engineer, Chat360', year: '2025', stack: 'Redis · Embeddings', status: 'In production', result: 'Fewer redundant LLM calls, lower latency.' },
  { name: 'INGESTION', short: 'INGESTION', cat: 'WORK', title: 'Agentic Ingestion Pipeline', summary: 'Scrapes target webpages with JinaAI, chunks the content and stores embeddings in Pinecone to power semantic search and grounded answers.', role: 'Backend AI Engineer Intern, Chat360', year: '2025', stack: 'JinaAI · Pinecone · Python', status: 'Shipped', result: 'Grounded query answering over client websites.' },
  { name: 'OPD CLAIMS', short: 'OPD CLAIMS', cat: 'PROJECTS', title: 'AI-Powered OPD Claim Adjudication', summary: 'Insurance rules plus LLM document analysis: Gemini turns prescriptions and invoices into structured claims, and Pinecone RAG over policies and past claims grounds each decision.', role: 'Self project', year: '2026', stack: 'FastAPI · React · TypeScript · Gemini · Pinecone · Firebase', status: 'Live', result: 'Confidence-aware routing with fraud detection, audit logs and manual review.', live: '#', source: '#' },
  { name: 'RL CONTROL', short: 'RL CONTROL', cat: 'RESEARCH', title: 'RL-Based Controller Design', summary: 'A TD3 reinforcement-learning controller pretrained on Model Predictive Control, with a Kalman filter for real-time state estimation, on a Quadruple Tank System.', role: 'Researcher, IIT Jodhpur', year: '2024', stack: 'Python · RL (TD3) · MPC · do-mpc', status: 'Completed', result: 'Under 1% steady-state error, converging in under 5 iterations.' },
  { name: 'F1 CLUB', short: 'F1 WEBSITE', cat: 'PROJECTS', title: 'Formula 1 Club Website', summary: 'A full-stack site for the IIT Jodhpur F1 club with live race updates, real-time chat, statistics filters and WebRTC race streaming.', role: 'Full-stack developer, IIT Jodhpur', year: '2024–25', stack: 'React · Node.js · MongoDB · WebRTC', status: 'Shipped', result: 'Live race coverage for the club.' },
];
const PROJECTS = [];
['A', 'B', 'C', 'D'].forEach((L, r) => [1, 2, 3].forEach((n, c) => {
  const i = r * 3 + c;
  PROJECTS.push({ code: L + n, row: r, col: c, color: cols[i], glyph: glyphs[i], ...ITEMS[i] });
}));
const byRow = (r) => PROJECTS.filter((p) => p.row === r);
const FILTERS = [['ALL', 12], ['WORK', 9], ['PROJECTS', 2], ['RESEARCH', 1]];
module.exports = { PROJECTS, byRow, FILTERS };
