/* Shared content for all three designs: the About copy and the long-form "read more" write-ups
   for the 12 projects. Edit text here once and every design picks it up.
   Facts come from the resume; anything marked TODO still needs Nikhil's input. */
window.PORTFOLIO = {
  person: {
    name: 'Nikhil Kumar',
    role: 'AI & Backend Engineer',
    email: 'nikhil385713@gmail.com',
    links: { github: '#', linkedin: '#', resume: '#' }, // TODO: real URLs
  },

  about: {
    headline: 'Chemical engineer by degree. Backend AI engineer by choice.',
    paras: [
      'I studied Chemical Engineering at IIT Jodhpur, and the part I liked most was control: getting a system to do what you ask, every time. My final-year research handed a four-tank water system to a reinforcement-learning agent. Watching its error drop under 1% is what pulled me into software.',
      'Now I am a Backend AI Engineer at Chat360. I build the parts of a chatbot nobody sees: memory that follows a customer from WhatsApp to the website, agents that hand work to each other in under five seconds, and logs that show a client every API call as it happens.',
      'I like problems that come with a number, like a latency budget, a match rate or a cost per query, because the number tells you when you are done. Competitive programming taught me the same habit. My best CodeChef finish was 43rd in the world in a Div 3 round.',
      'Away from work I follow Formula 1. I built the IIT Jodhpur F1 club’s website so we could follow race weekends together, with live updates, chat and a stream.',
    ],
    lookingFor: 'Teams shipping LLM products to real users, where the backend is the hard part.',
    facts: [
      ['Now', 'Backend AI Engineer, Chat360'],
      ['Studied', 'B.Tech Chemical Eng., IIT Jodhpur ’25'],
      ['School', 'Air Force School, Pune'],
      ['Ratings', 'CodeChef 1520 · LeetCode 1465'],
      ['Best rank', 'CodeChef global #43 (Starters 146)'],
      ['Open to', 'AI and backend engineering roles'],
    ],
  },

  projects: [
    {
      id: 'memory', code: 'A1', cat: 'WORK', color: '#ffd21f',
      title: 'Agentic Omnichannel Memory', org: 'Chat360', role: 'Backend AI Engineer', period: '2025 – present',
      stack: ['Python', 'LLMs', 'Customer Data Platform', 'Identity resolution'],
      status: 'In production',
      stat: ['98%', 'cross-channel identity match accuracy'],
      dek: 'One customer, five channels, one memory. Bots now remember who they are talking to, wherever the conversation started.',
      problem: 'A customer who messaged on WhatsApp yesterday and opens the website chat today looked like two strangers. Every channel kept its own history, so bots asked the same questions again and paid to process the same context twice.',
      built: [
        'A cross-channel identity-resolution layer spanning WhatsApp, website, Instagram, Messenger and voice.',
        'A multi-strategy identity resolver that links sessions to one customer profile, with zero orphaned sessions.',
        'Persistent short-term and long-term memory for agentic bots across sessions.',
        'A context-injection layer that feeds a configurable window of LLM-written session summaries into agent prompts.',
      ],
      how: [
        ['Ingest', 'Every inbound session arrives with whatever identifiers its channel exposes.'],
        ['Resolve', 'Several matching strategies run in turn to attach the session to one customer profile.'],
        ['Summarise', 'Finished sessions are condensed by an LLM into short summaries.'],
        ['Inject', 'The next conversation starts with a configurable window of those summaries in the prompt.'],
      ],
      outcome: '98% cross-channel match accuracy with zero orphaned sessions. Bots stopped re-collecting data the customer had already given, which also cut inference cost.',
    },
    {
      id: 'agents', code: 'A2', cat: 'WORK', color: '#2fd6c3',
      title: 'Multi-Agent Orchestration Framework', org: 'Chat360', role: 'Backend AI Engineer', period: '2025 – present',
      stack: ['LangGraph', 'MCP', 'Python asyncio', 'Caching'],
      status: 'In production',
      stat: ['<5s', 'round trip across the agent graph'],
      dek: 'Several specialist agents, one conversation, and an answer back in under five seconds.',
      problem: 'Multi-agent systems are easy to draw and slow to run: every hand-off between agents adds a model call and serialisation, and a chat user notices once a reply passes a few seconds.',
      built: [
        'A multi-agent orchestration system on LangGraph with asynchronous execution.',
        'Smart caching and optimised inter-agent message passing to keep hand-offs cheap.',
        'Model Context Protocol (MCP) integration for context propagation between agents.',
        'Dynamic invocation of both in-house and external tools through MCP.',
      ],
      how: [
        ['Route', 'A supervising graph decides which agents a message needs.'],
        ['Run in parallel', 'Independent agents execute asynchronously instead of in a chain.'],
        ['Share context', 'MCP carries context between agents and exposes tools to them.'],
        ['Cache', 'Repeated work is served from cache instead of re-running the model.'],
      ],
      outcome: 'End-to-end latency under 5 seconds for multi-agent conversations in production.',
    },
    {
      id: 'pdf-vision', code: 'A3', cat: 'WORK', color: '#ff5fa2',
      title: 'Multi-Modal PDF Image Retrieval', org: 'Chat360', role: 'Backend AI Engineer', period: '2025',
      stack: ['Pinecone', 'LLM captioning', 'RAG', 'PDF parsing'],
      status: 'In production',
      stat: ['1', 'reply with both the text and the image'],
      dek: 'The diagram on page 14 is now something the bot can find and show, not just the paragraph next to it.',
      problem: 'Retrieval pipelines read the text of a PDF and throw the images away, so a bot could describe a product diagram but never show it, unless the user uploaded it themselves.',
      built: [
        'An automated ingestion pipeline that extracts every image from a PDF.',
        'Context tracing that collects the headings, subheadings and nearby text around each image.',
        'LLM-generated captions built from that context.',
        'Pinecone indexing with the image URL stored as metadata.',
      ],
      how: [
        ['Extract', 'Pull images out of the PDF, page by page.'],
        ['Trace', 'Walk up to the nearest headings and grab the surrounding text.'],
        ['Caption', 'An LLM writes a searchable caption from that context.'],
        ['Index', 'Caption embeddings go into Pinecone with the image URL as metadata.'],
      ],
      outcome: 'The agent surfaces the relevant text and the relevant image together in one response, with no upload from the user.',
    },
    {
      id: 'auto-bot', code: 'B1', cat: 'WORK', color: '#4aa8ff',
      title: 'Automotive Conversational AI', org: 'Chat360', role: 'Backend AI Engineer', period: '2025',
      stack: ['Audio classification', 'Multimodal LLM', 'Python'],
      status: 'Proof of concept',
      stat: ['3', 'input types: text, image and engine audio'],
      dek: 'Record your engine, send it to the bot, and get a diagnosis.',
      problem: 'Car owners describe faults badly ("it makes a sort of knocking noise"), and support teams spend the first ten minutes of every call finding out which car it is.',
      built: [
        'User identification by phone number, with their vehicle data loaded automatically.',
        'Engine-fault diagnosis from uploaded audio using audio-classification models.',
        'Text, image and audio input in one conversation.',
        'Automatic hand-off of unresolved cases to the service-centre booking flow.',
      ],
      how: [
        ['Identify', 'The phone number finds the customer and their vehicle.'],
        ['Listen', 'An audio-classification model labels the engine recording.'],
        ['Explain', 'The bot turns the label and vehicle data into a plain answer.'],
        ['Escalate', 'Anything it cannot solve becomes a service booking.'],
      ],
      outcome: 'A working proof of concept for an automotive client: diagnosis from sound, with booking as the fallback.',
    },
    {
      id: 'api-logs', code: 'B2', cat: 'WORK', color: '#ff8a1f',
      title: 'Unified API Logging & Observability', org: 'Chat360', role: 'Backend AI Engineer', period: '2025',
      stack: ['Django', 'Celery', 'RabbitMQ', 'ClickHouse'],
      status: 'In production',
      stat: ['100%', 'of inbound API requests captured'],
      dek: 'Every inbound API call across every client campaign, searchable, without slowing a single request down.',
      problem: 'When a client asked "why did my campaign fail at 3am?", the answer was spread across server logs nobody could query quickly, and logging inline would have slowed every request.',
      built: [
        'Django middleware that intercepts each request without blocking it.',
        'A RabbitMQ broker that queues log events.',
        'Celery workers that drain the queue in the background.',
        'ClickHouse as the indexed sink, with a client-facing dashboard on top.',
      ],
      how: [
        ['Intercept', 'Middleware copies request and response metadata and returns immediately.'],
        ['Queue', 'Events go onto RabbitMQ.'],
        ['Drain', 'Celery workers batch them into ClickHouse.'],
        ['Inspect', 'Clients audit calls, trace latency and open failures from a dashboard.'],
      ],
      outcome: 'A client-facing dashboard for real-time API auditing, latency tracing and failure inspection across all campaigns.',
    },
    {
      id: 'ask-ai', code: 'B3', cat: 'WORK', color: '#a6ff3a',
      title: 'Cross-Channel “Ask-AI” Analytics Agent', org: 'Chat360', role: 'Backend AI Engineer', period: '2025',
      stack: ['Multi-agent', 'Natural-language analytics', 'Charts'],
      status: 'In production',
      stat: ['1', 'sentence to query every channel'],
      dek: '"How did last week’s campaign do on WhatsApp versus Instagram?" now has an answer, with a chart.',
      problem: 'Campaign numbers lived in a different screen for each channel. Comparing them meant exporting and stitching spreadsheets.',
      built: [
        'A product-wide natural-language analytics feature.',
        'A deterministic multi-agent pipeline that breaks a question into intents.',
        'Routing to channel-specific data fetchers.',
        'Answers rendered with auto-generated charts inline.',
      ],
      how: [
        ['Decompose', 'Split the question into per-channel, per-metric intents.'],
        ['Fetch', 'Each intent goes to the fetcher for its channel.'],
        ['Combine', 'Results are merged into one answer.'],
        ['Visualise', 'A chart is generated and shown inline.'],
      ],
      outcome: 'Users query campaign performance across channels in a single sentence and get charts back.',
    },
    {
      id: 'rag-tuning', code: 'C1', cat: 'WORK', color: '#ff5fa2',
      title: 'RAG Pipeline Optimization', org: 'Chat360', role: 'Backend AI Engineer', period: '2025',
      stack: ['RAG', 'Embeddings', 'Re-ranking', 'Chunking'],
      status: 'In production',
      stat: ['↓', 'embedding cost, ↑ retrieval quality'],
      dek: 'Better answers from the same documents, for less money.',
      problem: 'Bots were missing answers that were in the source material. Some content never made it through ingestion, and the rest was chunked in ways that split the answer in two.',
      built: [
        'Diagnosis of ingestion gaps in existing pipelines.',
        'Refined chunking and re-ranking strategies.',
        'Cheaper embedding models, deployed where quality allowed.',
        'Stronger cleaning for scraped web content before embedding.',
      ],
      how: [
        ['Audit', 'Find the questions that fail and trace where the content was lost.'],
        ['Clean', 'Strip navigation, boilerplate and noise from scraped pages.'],
        ['Re-chunk', 'Split on meaning, not character counts.'],
        ['Re-rank', 'Order retrieved chunks before they reach the model.'],
      ],
      outcome: 'Improved retrieval at a lower embedding cost across production RAG pipelines.',
    },
    {
      id: 'redis-cache', code: 'C2', cat: 'WORK', color: '#9a6bff',
      title: 'Redis Semantic Query Cache', org: 'Chat360', role: 'Backend AI Engineer', period: '2025',
      stack: ['Redis', 'Embeddings', 'Python'],
      status: 'In production',
      stat: ['0', 'LLM calls for a cached intent'],
      dek: 'If a hundred people ask the same thing in different words, the model only needs to answer once.',
      problem: 'High-frequency questions were sent to the model every time, paying for the same answer again and again and making users wait for it.',
      built: [
        'A Redis-backed semantic cache in front of the model.',
        'Matching on meaning, so reworded questions still hit the cache.',
        'Targeted at high-frequency intents.',
      ],
      how: [
        ['Embed', 'Turn the incoming query into a vector.'],
        ['Look up', 'Search Redis for a close-enough earlier query.'],
        ['Serve', 'On a hit, return the stored answer straight away.'],
        ['Store', 'On a miss, call the model and cache the result.'],
      ],
      outcome: 'Fewer redundant LLM calls and lower response latency for high-frequency intents.',
    },
    {
      id: 'ingestion', code: 'C3', cat: 'WORK', color: '#2fd6c3',
      title: 'Agentic Ingestion Pipeline', org: 'Chat360', role: 'Backend AI Engineer Intern', period: 'Jun – Aug 2025',
      stack: ['JinaAI', 'Pinecone', 'Python'],
      status: 'Shipped',
      stat: ['URL', 'in, grounded answers out'],
      dek: 'Point it at a website and the bot can answer questions about it.',
      problem: 'Setting up a bot for a new client meant someone copying their website content in by hand.',
      built: [
        'Scraping of target webpages with JinaAI.',
        'Chunking of the extracted content.',
        'Embeddings stored in Pinecone for semantic search.',
        'Alongside it: fixes for client-reported issues across several production GenAI products.',
      ],
      how: [
        ['Scrape', 'JinaAI reads the target pages.'],
        ['Chunk', 'Content is split into retrievable pieces.'],
        ['Embed', 'Chunks are embedded and written to Pinecone.'],
        ['Answer', 'The bot retrieves from Pinecone to ground its replies.'],
      ],
      outcome: 'Grounded question answering over client websites, built during the internship.',
    },
    {
      id: 'opd-claims', code: 'D1', cat: 'PROJECTS', color: '#ff8a1f',
      title: 'AI-Powered OPD Claim Adjudication', org: 'Self project', role: 'Solo builder', period: 'April 2026',
      stack: ['FastAPI', 'React', 'TypeScript', 'Gemini', 'Pinecone', 'Firebase'],
      status: 'Live',
      stat: ['RAG', 'grounded approve / reject decisions'],
      dek: 'Upload a prescription and an invoice; get a claim decision with the policy clause that justifies it.',
      problem: 'Outpatient (OPD) insurance claims are small and frequent, and still reviewed by hand against long policy documents.',
      built: [
        'A claim adjudication engine that combines insurance rules with LLM document analysis.',
        'A multimodal extraction pipeline that turns prescriptions and invoices into structured claim data with Gemini.',
        'A Pinecone RAG system over policy documents, medical guidelines and historical claims.',
        'Confidence-aware routing with fraud detection, audit logging and a manual-review queue.',
      ],
      how: [
        ['Extract', 'Gemini reads the uploaded documents into structured fields.'],
        ['Check rules', 'Hard policy rules run first.'],
        ['Ground', 'RAG retrieves the relevant policy text and similar past claims.'],
        ['Route', 'Confident decisions go through; low-confidence or suspicious ones go to a human.'],
      ],
      outcome: 'A working end-to-end platform with audit logs for every decision.',
      links: { live: '#', source: '#' }, // TODO: real URLs
    },
    {
      id: 'rl-control', code: 'D2', cat: 'RESEARCH', color: '#4aa8ff',
      title: 'RL-Based Controller Design', org: 'IIT Jodhpur', role: 'Researcher (supervisor: Dr. Santosh Kumar Varansi)', period: 'Aug – Nov 2024',
      stack: ['Python', 'RL (TD3)', 'MPC', 'do-mpc', 'Kalman filter'],
      status: 'Completed',
      stat: ['<1%', 'steady-state error, converged in under 5 iterations'],
      dek: 'Teach a reinforcement-learning agent by letting it watch an expert controller first.',
      problem: 'RL controllers learn by trial and error, which is unsafe on real plant equipment. MPC is safe but expensive to run online.',
      built: [
        'A TD3 reinforcement-learning controller pretrained to imitate Model Predictive Control.',
        'Dataset generation and predictive optimisation with do-mpc.',
        'A Kalman filter for real-time state estimation.',
        'Fault-tolerant control of a Quadruple Tank System.',
      ],
      how: [
        ['Generate', 'do-mpc produces expert MPC trajectories.'],
        ['Pretrain', 'The TD3 agent learns to copy them.'],
        ['Estimate', 'A Kalman filter supplies clean state readings.'],
        ['Adapt', 'The agent fine-tunes its policy safely from that starting point.'],
      ],
      outcome: 'Under 1% steady-state error with convergence in under 5 iterations: a hybrid MPC-RL setup for Industry 4.0 control.',
    },
    {
      id: 'f1-club', code: 'D3', cat: 'PROJECTS', color: '#ffd21f',
      title: 'Formula 1 Club Website', org: 'IIT Jodhpur', role: 'Full-stack developer (supervisor: Venkat Ram Reddy)', period: 'Dec 2024 – Jan 2025',
      stack: ['React', 'Node.js', 'MongoDB', 'WebRTC'],
      status: 'Shipped',
      stat: ['Live', 'race updates, chat and streaming'],
      dek: 'A race-weekend home for the IIT Jodhpur F1 club.',
      problem: 'Club members followed races across a dozen apps and group chats.',
      built: [
        'A full-stack web app with live Formula 1 race updates.',
        'Real-time chat for members during races.',
        'Dynamic statistics filters.',
        'WebRTC video streaming for live race coverage, with MongoDB for data.',
      ],
      how: [
        ['Feed', 'Live race data comes into the Node.js backend.'],
        ['Store', 'MongoDB holds stats and chat.'],
        ['Stream', 'WebRTC carries the live video.'],
        ['Show', 'React renders timing, filters and chat side by side.'],
      ],
      outcome: 'One page for the whole club on race day.',
    },
  ],
};
window.PORTFOLIO.byId = function (id) {
  var list = window.PORTFOLIO.projects;
  for (var i = 0; i < list.length; i++) if (list[i].id === id || list[i].code === id) return list[i];
  return list[0];
};
